---
title: "Advantage of Diversity"
subtitle: "Hybrid Surveys Improve Response Rates"
author: Jessica Im
format: pdf
date: "today"
date-format: long
editor: visual
bibliography: references.bib
---

```{r}
#| message: false
#| echo: false
#| warning: false


#### Work space set-up ####

library(tinytex)
library(tidyverse)
```

Digital modes of surveying have overcome common resource barriers like time and cost. Web surveys have also allowed for sampling across larger geographical areas and are easier to track using digital data collection and organization softwares. While web surveys have reduced a lot of manual labour, they are subject to sampling limitations like less representation for those without internet access or email addresses. They also struggle with having lower response rates than more analog or face-to-face modes of data collection ([@Daikeler]; [@Millar]; [@Sammut]). In “Special Virtual Issue on Nonresponse Rates and Nonresponse Adjustments” by the Journal of Survey Statistics and Methodology, declining response rates across different methods of data collection were discussed ([@SpecialVirtual]). It is argued that increasing digital modes of data collection had accelerated the decline of response rates. [@Daikeler] found that response rates to digital surveys were lower than rates for other modes of collection from 1997 to 2012, but stabilized between digital and non-digital from 2012 to 2016. COVID-19 accelerated digitization, with the average proportion of digital customer interactions jumping from 41% in December of 2019 to 65% 11 months later in North America [@McKinsey]. Despite digital surveys historically accumulating lower response rates than analog, increased digitization across industries indicates the importance of improving response rates for these modes of data collection.

Resulting from the lower response rates found, many researchers have endeavored to improve them. Multiple emails to remind participants have been shown to significantly increase response rates ([@Manzo]; [@Munoz]; [@Nulty]; [@Sammut]). [@Nulty] found that using no methods to boost response rates resulted in around 21.5% of responses while incentives and repeated reminder emails to students and survey holders had a 47% response rate. Kaplowitz et al. found that pre-notifications for web surveys increased response rate by around 10% (2004). In 2022, [@Wu] found that increasing the number of participants a survey was sent to did not impact response rate, but sending them to a specific sample did. They also found that sending multiple types of surveys like phone, mail, and fax, increased response rates.

Mixed-mode data collection provides the benefits of multiple modes while also offsetting the downsides of each mode within budget [@Leeuw]. By using the cheap method of data collection, researchers can cut costs to afford supportive data collection methods that may cost more. Using multiple modes helps to eliminate coverage bias present in digital forms of surveys so that participants with less digital access can still participate [@Leeuw]. Coverage bias can really harm sampling, especially since those with less digital access tend to be elderly, lower-income, or lower-educated persons. In addition to reducing coverage bias, mixed-modes can reduce nonresponse bias. Telephone follow-ups for nonrespondents after a large mail survey followed by another face-to-face interview greatly reduced nonresponse bias in the American Community Survey. [@Wu] also found that telephone follow-ups after a web survey was released increased response rates. In 2020, [@Monzon] showed that hybrid survey methods increased response rates by up to 22%, resulting in a cost-effective compromise between online and in-person surveys.

The increase in digital modes of surveying has helped overcome many physical and resource barriers to data collection, but has also brought on its own unique challenges. The implementation of intervention strategies like reminders and incentives have shown to reduce nonresponse and coverage bias. Using mixed-modes has also improved sampling validity without largely increasing costs. As technology continues to rapidly develop, survey owners must adjust to changing methods, and keep watch as participants undoubtedly adapt.

# References

[@Manual]
[@Article]